[package]
name = "fib"
version = "0.1.0"
authors = ["Brett Holman <bpholman5@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotlib = "0.5.1"